//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR2024.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PR2024Entitiesss : DbContext
    {
        public PR2024Entitiesss()
            : base("name=PR2024Entitiesss")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agents> Agents { get; set; }
        public virtual DbSet<Apartments> Apartments { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Deals> Deals { get; set; }
        public virtual DbSet<Demand_Apartments> Demand_Apartments { get; set; }
        public virtual DbSet<Demand_Houses> Demand_Houses { get; set; }
        public virtual DbSet<Demand_Lands> Demand_Lands { get; set; }
        public virtual DbSet<Demands> Demands { get; set; }
        public virtual DbSet<Districts> Districts { get; set; }
        public virtual DbSet<Houses> Houses { get; set; }
        public virtual DbSet<Lands> Lands { get; set; }
        public virtual DbSet<RealEstates> RealEstates { get; set; }
        public virtual DbSet<Supply> Supply { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
